type ExternalSourceSeed = {
  name: string;
  sourceType:
    | 'municipality'
    | 'province'
    | 'national_department'
    | 'soe'
    | 'university'
    | 'tvet'
    | 'public_entity'
    | 'pdf_bulletin'
    | 'other';
  baseUrl: string;
  tenderUrl: string;
  province: string | null;
  organisationName: string;
  scrapeMethod: 'static_html' | 'dynamic_browser' | 'pdf' | 'mixed';
  active: boolean;
  scrapeFrequencyHours: number;
  scrapeFrequencyMinutes: number;
};

function source(
  name: string,
  sourceType: ExternalSourceSeed['sourceType'],
  baseUrl: string,
  tenderUrl: string,
  province: string | null,
  organisationName = name.replace(/ Tenders$/, ''),
  scrapeMethod: ExternalSourceSeed['scrapeMethod'] = 'mixed',
): ExternalSourceSeed {
  return {
    name,
    sourceType,
    baseUrl,
    tenderUrl,
    province,
    organisationName,
    scrapeMethod,
    active: true,
    scrapeFrequencyHours: 1,
    scrapeFrequencyMinutes: 30,
  };
}

function searchSource(
  platform: string,
  template: string,
  query: string,
): ExternalSourceSeed {
  const encodedQuery = encodeURIComponent(query);

  return {
    ...source(
    `${platform} Search - ${query}`,
    'other',
    new URL(template.replace('{query}', encodedQuery)).origin,
    template.replace('{query}', encodedQuery),
    null,
    platform,
    'mixed',
    ),
    active: false,
    scrapeFrequencyHours: 24,
    scrapeFrequencyMinutes: 24 * 60,
  };
}

const searchProvinces = [
  'Eastern Cape',
  'Free State',
  'Gauteng',
  'KwaZulu-Natal',
  'Limpopo',
  'Mpumalanga',
  'North West',
  'Northern Cape',
  'Western Cape',
];

const tenderSearchCategories = [
  'construction tenders',
  'building maintenance tenders',
  'civil engineering tenders',
  'road maintenance tenders',
  'water infrastructure tenders',
  'electricity tenders',
  'solar tenders',
  'cleaning tenders',
  'security tenders',
  'catering tenders',
  'transport tenders',
  'fleet tenders',
  'courier tenders',
  'ICT tenders',
  'software tenders',
  'network support tenders',
  'computer equipment tenders',
  'office furniture tenders',
  'stationery tenders',
  'printing tenders',
  'medical equipment tenders',
  'pharmaceutical tenders',
  'PPE tenders',
  'waste management tenders',
  'gardening tenders',
  'landscaping tenders',
  'training tenders',
  'consulting tenders',
  'audit tenders',
  'legal services tenders',
  'insurance tenders',
  'travel management tenders',
  'events tenders',
  'accommodation tenders',
  'food supply tenders',
  'school nutrition tenders',
  'laboratory services tenders',
  'professional services tenders',
  'engineering services tenders',
  'asset management tenders',
  'facilities management tenders',
  'fire services tenders',
  'occupational health tenders',
  'research tenders',
  'communications tenders',
  'media monitoring tenders',
  'call centre tenders',
  'recruitment tenders',
  'vehicle hire tenders',
  'fuel tenders',
];

const tenderAdvertisingSearchPlatforms = [
  {
    name: 'Tender Bulletins',
    template: 'https://www.tenderbulletins.co.za/?s={query}',
  },
  {
    name: 'Online Tenders',
    template:
      'https://www.onlinetenders.co.za/tenders/south-africa?search={query}',
  },
  {
    name: 'TenderAlerts',
    template: 'https://tenderalerts.co.za/tenders/?search={query}',
  },
  {
    name: 'EasyTenders',
    template: 'https://easytenders.co.za/tenders?search={query}',
  },
  {
    name: 'Leads 2 Business',
    template: 'https://www.l2b.co.za/Search/GlobalSearch?searchText={query}',
  },
  {
    name: 'SA-Tenders',
    template: 'https://www.sa-tenders.co.za/search/node/{query}',
  },
];

const generatedTenderAdvertisingSources = searchProvinces.flatMap((province) =>
  tenderSearchCategories.flatMap((category) =>
    tenderAdvertisingSearchPlatforms.map((platform) =>
      searchSource(platform.name, platform.template, `${province} ${category}`),
    ),
  ),
);

const curatedSouthAfricanExternalSources: ExternalSourceSeed[] = [
  source(
    'City of Johannesburg Tenders',
    'municipality',
    'https://joburg.org.za',
    'https://joburg.org.za/work_/TendersQuotations/Pages/Tenders.aspx',
    'Gauteng',
    'City of Johannesburg Metropolitan Municipality',
    'static_html',
  ),
  source(
    'Western Cape Government Tenders',
    'province',
    'https://www.westerncape.gov.za',
    'https://www.westerncape.gov.za/tenders',
    'Western Cape',
    'Western Cape Government',
    'static_html',
  ),
  source(
    'Transnet Tenders',
    'soe',
    'https://www.transnet.net',
    'https://www.transnet.net/TransnetTenders',
    null,
    'Transnet SOC Ltd',
    'static_html',
  ),
  source(
    'Eskom Tender Bulletin',
    'soe',
    'https://tenderbulletin.eskom.co.za',
    'https://tenderbulletin.eskom.co.za/',
    null,
    'Eskom Holdings SOC Ltd',
    'static_html',
  ),
  source(
    'Gauteng Provincial Government Tenders',
    'province',
    'https://www.gauteng.gov.za',
    'https://www.gauteng.gov.za/Services/GetServices?serviceId=CPM-001490',
    'Gauteng',
    'Gauteng Provincial Government',
    'static_html',
  ),
  source(
    'SANRAL Tenders',
    'public_entity',
    'https://www.nra.co.za',
    'https://www.nra.co.za/sanral-tenders/status',
    null,
    'South African National Roads Agency SOC Ltd',
    'static_html',
  ),

  source(
    'City of Cape Town Tenders',
    'municipality',
    'https://www.capetown.gov.za',
    'https://www.capetown.gov.za/City-Connect/Business-and-trade/Tenders-quotations-and-supply-chain-management/Tenders',
    'Western Cape',
    'City of Cape Town Metropolitan Municipality',
  ),
  source(
    'City of Tshwane Tenders',
    'municipality',
    'https://www.tshwane.gov.za',
    'https://www.tshwane.gov.za/?page_id=15871',
    'Gauteng',
    'City of Tshwane Metropolitan Municipality',
  ),
  source(
    'City of Ekurhuleni Tenders',
    'municipality',
    'https://www.ekurhuleni.gov.za',
    'https://www.ekurhuleni.gov.za/business/tenders/',
    'Gauteng',
    'City of Ekurhuleni Metropolitan Municipality',
  ),
  source(
    'eThekwini Municipality Tenders',
    'municipality',
    'https://www.durban.gov.za',
    'https://www.durban.gov.za/pages/business/tenders',
    'KwaZulu-Natal',
    'eThekwini Metropolitan Municipality',
  ),
  source(
    'Buffalo City Tenders',
    'municipality',
    'https://www.buffalocity.gov.za',
    'https://www.buffalocity.gov.za/tenders',
    'Eastern Cape',
    'Buffalo City Metropolitan Municipality',
  ),
  source(
    'Nelson Mandela Bay Tenders',
    'municipality',
    'https://www.nelsonmandelabay.gov.za',
    'https://www.nelsonmandelabay.gov.za/page/tenders',
    'Eastern Cape',
    'Nelson Mandela Bay Metropolitan Municipality',
  ),
  source(
    'Mangaung Tenders',
    'municipality',
    'https://www.mangaung.co.za',
    'https://www.mangaung.co.za/category/tenders/',
    'Free State',
    'Mangaung Metropolitan Municipality',
  ),
  source(
    'Johannesburg Water Tenders',
    'public_entity',
    'https://www.johannesburgwater.co.za',
    'https://www.johannesburgwater.co.za/supply-chain-management/tenders/',
    'Gauteng',
    'Johannesburg Water SOC Ltd',
  ),
  source(
    'Rand Water Tenders',
    'public_entity',
    'https://www.randwater.co.za',
    'https://www.randwater.co.za/procurement/tenders/',
    'Gauteng',
    'Rand Water',
  ),
  source(
    'Umgeni Water Tenders',
    'public_entity',
    'https://umgeni.co.za',
    'https://umgeni.co.za/tenders/',
    'KwaZulu-Natal',
    'Umgeni Water',
  ),
  source(
    'Lepelle Northern Water Tenders',
    'public_entity',
    'https://lepellewater.co.za',
    'https://lepellewater.co.za/tenders/',
    'Limpopo',
    'Lepelle Northern Water',
  ),
  source(
    'Bloem Water Tenders',
    'public_entity',
    'https://www.bloemwater.co.za',
    'https://www.bloemwater.co.za/tenders/',
    'Free State',
    'Bloem Water',
  ),
  source(
    'Magalies Water Tenders',
    'public_entity',
    'https://www.magalieswater.co.za',
    'https://www.magalieswater.co.za/tenders/',
    'North West',
    'Magalies Water',
  ),
  source(
    'PRASA Tenders',
    'soe',
    'https://www.prasa.com',
    'https://www.prasa.com/Tenders.html',
    null,
    'Passenger Rail Agency of South Africa',
  ),
  source(
    'Airports Company South Africa Tenders',
    'soe',
    'https://www.airports.co.za',
    'https://www.airports.co.za/business/tenders',
    null,
    'Airports Company South Africa SOC Ltd',
  ),
  source(
    'SITA Tenders',
    'public_entity',
    'https://www.sita.co.za',
    'https://www.sita.co.za/procurement/tenders',
    null,
    'State Information Technology Agency',
  ),
  source(
    'SABC Tenders',
    'soe',
    'https://www.sabc.co.za',
    'https://www.sabc.co.za/sabc/tenders/',
    null,
    'South African Broadcasting Corporation SOC Ltd',
  ),
  source(
    'Sentech Tenders',
    'soe',
    'https://www.sentech.co.za',
    'https://www.sentech.co.za/tenders/',
    null,
    'Sentech SOC Ltd',
  ),
  source(
    'PetroSA Tenders',
    'soe',
    'https://www.petrosa.co.za',
    'https://www.petrosa.co.za/procurement/tenders/',
    null,
    'PetroSA SOC Ltd',
  ),
  source(
    'Denel Tenders',
    'soe',
    'https://www.denel.co.za',
    'https://www.denel.co.za/tenders',
    null,
    'Denel SOC Ltd',
  ),
  source(
    'Armscor Tenders',
    'public_entity',
    'https://www.armscor.co.za',
    'https://www.armscor.co.za/tenders/',
    null,
    'Armscor',
  ),
  source(
    'AEMFC Tenders',
    'soe',
    'https://www.aemfc.co.za',
    'https://www.aemfc.co.za/tenders/',
    'Gauteng',
    'African Exploration Mining and Finance Corporation',
  ),
  source(
    'SAFCOL Tenders',
    'soe',
    'https://www.safcol.co.za',
    'https://www.safcol.co.za/tenders/',
    'Mpumalanga',
    'South African Forestry Company SOC Ltd',
  ),
  source(
    'SARS Tenders',
    'national_department',
    'https://www.sars.gov.za',
    'https://www.sars.gov.za/procurement/tenders/',
    null,
    'South African Revenue Service',
  ),
  source(
    'CIPC Tenders',
    'public_entity',
    'https://www.cipc.co.za',
    'https://www.cipc.co.za/?page_id=1695',
    null,
    'Companies and Intellectual Property Commission',
  ),
  source(
    'CSIR Tenders',
    'public_entity',
    'https://www.csir.co.za',
    'https://www.csir.co.za/tenders',
    'Gauteng',
    'Council for Scientific and Industrial Research',
  ),
  source(
    'SANParks Tenders',
    'public_entity',
    'https://www.sanparks.org',
    'https://www.sanparks.org/corporate/tenders/',
    null,
    'South African National Parks',
  ),
  source(
    'National Research Foundation Tenders',
    'public_entity',
    'https://www.nrf.ac.za',
    'https://www.nrf.ac.za/procurement/tenders/',
    null,
    'National Research Foundation',
  ),
  source(
    'Agricultural Research Council Tenders',
    'public_entity',
    'https://www.arc.agric.za',
    'https://www.arc.agric.za/Pages/Tenders.aspx',
    null,
    'Agricultural Research Council',
  ),
  source(
    'Water Research Commission Tenders',
    'public_entity',
    'https://www.wrc.org.za',
    'https://www.wrc.org.za/tenders/',
    'Gauteng',
    'Water Research Commission',
  ),
  source(
    'Industrial Development Corporation Tenders',
    'public_entity',
    'https://www.idc.co.za',
    'https://www.idc.co.za/procurement/',
    'Gauteng',
    'Industrial Development Corporation',
  ),
  source(
    'Development Bank of Southern Africa Tenders',
    'public_entity',
    'https://www.dbsa.org',
    'https://www.dbsa.org/procurement',
    'Gauteng',
    'Development Bank of Southern Africa',
  ),
  source(
    'Independent Development Trust Tenders',
    'public_entity',
    'https://www.idt.org.za',
    'https://www.idt.org.za/business-opportunities/tenders/',
    null,
    'Independent Development Trust',
  ),
  source(
    'South African Weather Service Tenders',
    'public_entity',
    'https://www.weathersa.co.za',
    'https://www.weathersa.co.za/home/tenders',
    'Gauteng',
    'South African Weather Service',
  ),
  source(
    'South African Tourism Tenders',
    'public_entity',
    'https://www.southafrica.net',
    'https://www.southafrica.net/gl/en/corporate/page/tenders',
    null,
    'South African Tourism',
  ),
  source(
    'National Lotteries Commission Tenders',
    'public_entity',
    'https://www.nlcsa.org.za',
    'https://www.nlcsa.org.za/tenders/',
    null,
    'National Lotteries Commission',
  ),
  source(
    'Road Accident Fund Tenders',
    'public_entity',
    'https://www.raf.co.za',
    'https://www.raf.co.za/tenders',
    null,
    'Road Accident Fund',
  ),
  source(
    'Road Traffic Management Corporation Tenders',
    'public_entity',
    'https://www.rtmc.co.za',
    'https://www.rtmc.co.za/index.php/tenders',
    null,
    'Road Traffic Management Corporation',
  ),
  source(
    'Railway Safety Regulator Tenders',
    'public_entity',
    'https://www.rsr.org.za',
    'https://www.rsr.org.za/tenders/',
    null,
    'Railway Safety Regulator',
  ),
  source(
    'SAMSA Tenders',
    'public_entity',
    'https://www.samsa.org.za',
    'https://www.samsa.org.za/tenders/',
    null,
    'South African Maritime Safety Authority',
  ),
  source(
    'Cross-Border Road Transport Agency Tenders',
    'public_entity',
    'https://www.cbrta.co.za',
    'https://www.cbrta.co.za/tenders/',
    null,
    'Cross-Border Road Transport Agency',
  ),
  source(
    'National Department of Health Tenders',
    'national_department',
    'https://www.health.gov.za',
    'https://www.health.gov.za/tenders/',
    null,
    'National Department of Health',
  ),
  source(
    'Department of Basic Education Tenders',
    'national_department',
    'https://www.education.gov.za',
    'https://www.education.gov.za/Informationfor/Procurement/Tenders.aspx',
    null,
    'Department of Basic Education',
  ),
  source(
    'Department of Higher Education and Training Tenders',
    'national_department',
    'https://www.dhet.gov.za',
    'https://www.dhet.gov.za/SitePages/Tenders.aspx',
    null,
    'Department of Higher Education and Training',
  ),
  source(
    'Department of Home Affairs Tenders',
    'national_department',
    'https://www.dha.gov.za',
    'https://www.dha.gov.za/index.php/tenders',
    null,
    'Department of Home Affairs',
  ),
  source(
    'Department of Public Works and Infrastructure Tenders',
    'national_department',
    'https://www.publicworks.gov.za',
    'https://www.publicworks.gov.za/tenders.html',
    null,
    'Department of Public Works and Infrastructure',
  ),
  source(
    'Department of Water and Sanitation Tenders',
    'national_department',
    'https://www.dws.gov.za',
    'https://www.dws.gov.za/Tenders/',
    null,
    'Department of Water and Sanitation',
  ),
  source(
    'Department of Transport Tenders',
    'national_department',
    'https://www.transport.gov.za',
    'https://www.transport.gov.za/tenders',
    null,
    'Department of Transport',
  ),
  source(
    'Department of Agriculture Tenders',
    'national_department',
    'https://www.dalrrd.gov.za',
    'https://www.dalrrd.gov.za/tenders',
    null,
    'Department of Agriculture, Land Reform and Rural Development',
  ),
  source(
    'Department of Forestry Fisheries and Environment Tenders',
    'national_department',
    'https://www.dffe.gov.za',
    'https://www.dffe.gov.za/tenders',
    null,
    'Department of Forestry, Fisheries and the Environment',
  ),
  source(
    'Statistics South Africa Tenders',
    'national_department',
    'https://www.statssa.gov.za',
    'https://www.statssa.gov.za/?page_id=455',
    null,
    'Statistics South Africa',
  ),

  source(
    'Stellenbosch Municipality Tenders',
    'municipality',
    'https://stellenbosch.gov.za',
    'https://stellenbosch.gov.za/tenders/',
    'Western Cape',
    'Stellenbosch Local Municipality',
  ),
  source(
    'Drakenstein Municipality Tenders',
    'municipality',
    'https://www.drakenstein.gov.za',
    'https://www.drakenstein.gov.za/business/tenders',
    'Western Cape',
    'Drakenstein Local Municipality',
  ),
  source(
    'George Municipality Tenders',
    'municipality',
    'https://www.george.gov.za',
    'https://www.george.gov.za/tenders/',
    'Western Cape',
    'George Local Municipality',
  ),
  source(
    'Mossel Bay Municipality Tenders',
    'municipality',
    'https://www.mosselbay.gov.za',
    'https://www.mosselbay.gov.za/tenders',
    'Western Cape',
    'Mossel Bay Local Municipality',
  ),
  source(
    'Overstrand Municipality Tenders',
    'municipality',
    'https://www.overstrand.gov.za',
    'https://www.overstrand.gov.za/en/documents/tenders',
    'Western Cape',
    'Overstrand Local Municipality',
  ),
  source(
    'Swartland Municipality Tenders',
    'municipality',
    'https://swartland.org.za',
    'https://swartland.org.za/pages/english/tenders.php',
    'Western Cape',
    'Swartland Local Municipality',
  ),
  source(
    'Saldanha Bay Municipality Tenders',
    'municipality',
    'https://sbm.gov.za',
    'https://sbm.gov.za/tenders/',
    'Western Cape',
    'Saldanha Bay Local Municipality',
  ),
  source(
    'Knysna Municipality Tenders',
    'municipality',
    'https://www.knysna.gov.za',
    'https://www.knysna.gov.za/tenders/',
    'Western Cape',
    'Knysna Local Municipality',
  ),
  source(
    'Oudtshoorn Municipality Tenders',
    'municipality',
    'https://www.oudtshoorn.gov.za',
    'https://www.oudtshoorn.gov.za/tenders/',
    'Western Cape',
    'Oudtshoorn Local Municipality',
  ),
  source(
    'Bitou Municipality Tenders',
    'municipality',
    'https://www.bitou.gov.za',
    'https://www.bitou.gov.za/tenders',
    'Western Cape',
    'Bitou Local Municipality',
  ),
  source(
    'Hessequa Municipality Tenders',
    'municipality',
    'https://www.hessequa.gov.za',
    'https://www.hessequa.gov.za/tenders/',
    'Western Cape',
    'Hessequa Local Municipality',
  ),
  source(
    'Theewaterskloof Municipality Tenders',
    'municipality',
    'https://www.twk.gov.za',
    'https://www.twk.gov.za/tenders/',
    'Western Cape',
    'Theewaterskloof Local Municipality',
  ),
  source(
    'Breede Valley Municipality Tenders',
    'municipality',
    'https://www.bvm.gov.za',
    'https://www.bvm.gov.za/tenders/',
    'Western Cape',
    'Breede Valley Local Municipality',
  ),
  source(
    'Bergrivier Municipality Tenders',
    'municipality',
    'https://www.bergmun.org.za',
    'https://www.bergmun.org.za/tenders',
    'Western Cape',
    'Bergrivier Local Municipality',
  ),
  source(
    'Garden Route District Municipality Tenders',
    'municipality',
    'https://www.gardenroute.gov.za',
    'https://www.gardenroute.gov.za/tenders/',
    'Western Cape',
    'Garden Route District Municipality',
  ),
  source(
    'West Coast District Municipality Tenders',
    'municipality',
    'https://westcoastdm.co.za',
    'https://westcoastdm.co.za/tenders/',
    'Western Cape',
    'West Coast District Municipality',
  ),
  source(
    'Cape Winelands District Municipality Tenders',
    'municipality',
    'https://www.capewinelands.gov.za',
    'https://www.capewinelands.gov.za/tenders/',
    'Western Cape',
    'Cape Winelands District Municipality',
  ),
  source(
    'Overberg District Municipality Tenders',
    'municipality',
    'https://www.odm.org.za',
    'https://www.odm.org.za/tenders/',
    'Western Cape',
    'Overberg District Municipality',
  ),
  source(
    'Central Karoo District Municipality Tenders',
    'municipality',
    'https://www.skdm.co.za',
    'https://www.skdm.co.za/tenders/',
    'Western Cape',
    'Central Karoo District Municipality',
  ),

  source(
    'Kouga Municipality Tenders',
    'municipality',
    'https://www.kouga.gov.za',
    'https://www.kouga.gov.za/tenders',
    'Eastern Cape',
    'Kouga Local Municipality',
  ),
  source(
    'Sarah Baartman District Municipality Tenders',
    'municipality',
    'https://www.sarahbaartman.co.za',
    'https://www.sarahbaartman.co.za/tenders',
    'Eastern Cape',
    'Sarah Baartman District Municipality',
  ),
  source(
    'Amathole District Municipality Tenders',
    'municipality',
    'https://www.amathole.gov.za',
    'https://www.amathole.gov.za/tenders/',
    'Eastern Cape',
    'Amathole District Municipality',
  ),
  source(
    'Chris Hani District Municipality Tenders',
    'municipality',
    'https://www.chrishanidm.gov.za',
    'https://www.chrishanidm.gov.za/tenders/',
    'Eastern Cape',
    'Chris Hani District Municipality',
  ),
  source(
    'Joe Gqabi District Municipality Tenders',
    'municipality',
    'https://www.jgdm.gov.za',
    'https://www.jgdm.gov.za/tenders/',
    'Eastern Cape',
    'Joe Gqabi District Municipality',
  ),
  source(
    'OR Tambo District Municipality Tenders',
    'municipality',
    'https://www.ortambodm.gov.za',
    'https://www.ortambodm.gov.za/tenders/',
    'Eastern Cape',
    'OR Tambo District Municipality',
  ),
  source(
    'Alfred Nzo District Municipality Tenders',
    'municipality',
    'https://www.andm.gov.za',
    'https://www.andm.gov.za/tenders/',
    'Eastern Cape',
    'Alfred Nzo District Municipality',
  ),
  source(
    'King Sabata Dalindyebo Municipality Tenders',
    'municipality',
    'https://www.ksd.gov.za',
    'https://www.ksd.gov.za/tenders/',
    'Eastern Cape',
    'King Sabata Dalindyebo Local Municipality',
  ),
  source(
    'Makana Municipality Tenders',
    'municipality',
    'https://www.makana.gov.za',
    'https://www.makana.gov.za/tenders/',
    'Eastern Cape',
    'Makana Local Municipality',
  ),
  source(
    'Ndlambe Municipality Tenders',
    'municipality',
    'https://www.ndlambe.gov.za',
    'https://www.ndlambe.gov.za/tenders/',
    'Eastern Cape',
    'Ndlambe Local Municipality',
  ),
  source(
    'Raymond Mhlaba Municipality Tenders',
    'municipality',
    'https://www.raymondmhlaba.gov.za',
    'https://www.raymondmhlaba.gov.za/tenders/',
    'Eastern Cape',
    'Raymond Mhlaba Local Municipality',
  ),
  source(
    'Matatiele Municipality Tenders',
    'municipality',
    'https://www.matatiele.gov.za',
    'https://www.matatiele.gov.za/tenders/',
    'Eastern Cape',
    'Matatiele Local Municipality',
  ),

  source(
    'Msunduzi Municipality Tenders',
    'municipality',
    'https://www.msunduzi.gov.za',
    'https://www.msunduzi.gov.za/site/tenders',
    'KwaZulu-Natal',
    'Msunduzi Local Municipality',
  ),
  source(
    'uMhlathuze Municipality Tenders',
    'municipality',
    'https://www.umhlathuze.gov.za',
    'https://www.umhlathuze.gov.za/tenders',
    'KwaZulu-Natal',
    'uMhlathuze Local Municipality',
  ),
  source(
    'KwaDukuza Municipality Tenders',
    'municipality',
    'https://www.kwadukuza.gov.za',
    'https://www.kwadukuza.gov.za/tenders',
    'KwaZulu-Natal',
    'KwaDukuza Local Municipality',
  ),
  source(
    'Newcastle Municipality Tenders',
    'municipality',
    'https://www.newcastle.gov.za',
    'https://www.newcastle.gov.za/tenders',
    'KwaZulu-Natal',
    'Newcastle Local Municipality',
  ),
  source(
    'Ray Nkonyeni Municipality Tenders',
    'municipality',
    'https://www.rnm.gov.za',
    'https://www.rnm.gov.za/tenders/',
    'KwaZulu-Natal',
    'Ray Nkonyeni Local Municipality',
  ),
  source(
    'Ugu District Municipality Tenders',
    'municipality',
    'https://www.ugu.gov.za',
    'https://www.ugu.gov.za/tenders/',
    'KwaZulu-Natal',
    'Ugu District Municipality',
  ),
  source(
    'uMgungundlovu District Municipality Tenders',
    'municipality',
    'https://www.umdm.gov.za',
    'https://www.umdm.gov.za/tenders/',
    'KwaZulu-Natal',
    'uMgungundlovu District Municipality',
  ),
  source(
    'uThukela District Municipality Tenders',
    'municipality',
    'https://uthukeladm.co.za',
    'https://uthukeladm.co.za/tenders/',
    'KwaZulu-Natal',
    'uThukela District Municipality',
  ),
  source(
    'King Cetshwayo District Municipality Tenders',
    'municipality',
    'https://kingcetshwayo.gov.za',
    'https://kingcetshwayo.gov.za/tenders/',
    'KwaZulu-Natal',
    'King Cetshwayo District Municipality',
  ),
  source(
    'Zululand District Municipality Tenders',
    'municipality',
    'https://www.zululand.org.za',
    'https://www.zululand.org.za/tenders/',
    'KwaZulu-Natal',
    'Zululand District Municipality',
  ),
  source(
    'Amajuba District Municipality Tenders',
    'municipality',
    'https://amajuba.gov.za',
    'https://amajuba.gov.za/tenders/',
    'KwaZulu-Natal',
    'Amajuba District Municipality',
  ),
  source(
    'Harry Gwala District Municipality Tenders',
    'municipality',
    'https://www.harrygwaladm.gov.za',
    'https://www.harrygwaladm.gov.za/tenders/',
    'KwaZulu-Natal',
    'Harry Gwala District Municipality',
  ),
  source(
    'uMkhanyakude District Municipality Tenders',
    'municipality',
    'https://www.ukdm.gov.za',
    'https://www.ukdm.gov.za/tenders/',
    'KwaZulu-Natal',
    'uMkhanyakude District Municipality',
  ),
  source(
    'Dr Nkosazana Dlamini-Zuma Municipality Tenders',
    'municipality',
    'https://www.ndz.gov.za',
    'https://www.ndz.gov.za/tenders/',
    'KwaZulu-Natal',
    'Dr Nkosazana Dlamini-Zuma Local Municipality',
  ),

  source(
    'Polokwane Municipality Tenders',
    'municipality',
    'https://www.polokwane.gov.za',
    'https://www.polokwane.gov.za/Business/Pages/Tenders.aspx',
    'Limpopo',
    'Polokwane Local Municipality',
  ),
  source(
    'Mogalakwena Municipality Tenders',
    'municipality',
    'https://www.mogalakwena.gov.za',
    'https://www.mogalakwena.gov.za/tenders/',
    'Limpopo',
    'Mogalakwena Local Municipality',
  ),
  source(
    'Thulamela Municipality Tenders',
    'municipality',
    'https://www.thulamela.gov.za',
    'https://www.thulamela.gov.za/tenders/',
    'Limpopo',
    'Thulamela Local Municipality',
  ),
  source(
    'Makhado Municipality Tenders',
    'municipality',
    'https://www.makhado.gov.za',
    'https://www.makhado.gov.za/tenders/',
    'Limpopo',
    'Makhado Local Municipality',
  ),
  source(
    'Greater Tzaneen Municipality Tenders',
    'municipality',
    'https://www.greatertzaneen.gov.za',
    'https://www.greatertzaneen.gov.za/tenders/',
    'Limpopo',
    'Greater Tzaneen Local Municipality',
  ),
  source(
    'Ba-Phalaborwa Municipality Tenders',
    'municipality',
    'https://www.ba-phalaborwa.gov.za',
    'https://www.ba-phalaborwa.gov.za/tenders/',
    'Limpopo',
    'Ba-Phalaborwa Local Municipality',
  ),
  source(
    'Lephalale Municipality Tenders',
    'municipality',
    'https://www.lephalale.gov.za',
    'https://www.lephalale.gov.za/tenders/',
    'Limpopo',
    'Lephalale Local Municipality',
  ),
  source(
    'Fetakgomo Tubatse Municipality Tenders',
    'municipality',
    'https://www.ftlm.gov.za',
    'https://www.ftlm.gov.za/tenders/',
    'Limpopo',
    'Fetakgomo Tubatse Local Municipality',
  ),
  source(
    'Capricorn District Municipality Tenders',
    'municipality',
    'https://www.cdm.org.za',
    'https://www.cdm.org.za/tenders/',
    'Limpopo',
    'Capricorn District Municipality',
  ),
  source(
    'Mopani District Municipality Tenders',
    'municipality',
    'https://www.mopani.gov.za',
    'https://www.mopani.gov.za/tenders/',
    'Limpopo',
    'Mopani District Municipality',
  ),
  source(
    'Vhembe District Municipality Tenders',
    'municipality',
    'https://www.vhembe.gov.za',
    'https://www.vhembe.gov.za/tenders/',
    'Limpopo',
    'Vhembe District Municipality',
  ),
  source(
    'Waterberg District Municipality Tenders',
    'municipality',
    'https://waterberg.gov.za',
    'https://waterberg.gov.za/tenders/',
    'Limpopo',
    'Waterberg District Municipality',
  ),
  source(
    'Sekhukhune District Municipality Tenders',
    'municipality',
    'https://www.sekhukhunedistrict.gov.za',
    'https://www.sekhukhunedistrict.gov.za/tenders/',
    'Limpopo',
    'Sekhukhune District Municipality',
  ),

  source(
    'City of Mbombela Tenders',
    'municipality',
    'https://www.mbombela.gov.za',
    'https://www.mbombela.gov.za/tenders.html',
    'Mpumalanga',
    'City of Mbombela Local Municipality',
  ),
  source(
    'Emalahleni Municipality Tenders',
    'municipality',
    'https://www.emalahleni.gov.za',
    'https://www.emalahleni.gov.za/tenders/',
    'Mpumalanga',
    'Emalahleni Local Municipality',
  ),
  source(
    'Steve Tshwete Municipality Tenders',
    'municipality',
    'https://www.stlm.gov.za',
    'https://www.stlm.gov.za/tenders/',
    'Mpumalanga',
    'Steve Tshwete Local Municipality',
  ),
  source(
    'Govan Mbeki Municipality Tenders',
    'municipality',
    'https://www.govanmbeki.gov.za',
    'https://www.govanmbeki.gov.za/tenders/',
    'Mpumalanga',
    'Govan Mbeki Local Municipality',
  ),
  source(
    'Bushbuckridge Municipality Tenders',
    'municipality',
    'https://www.bushbuckridge.gov.za',
    'https://www.bushbuckridge.gov.za/tenders/',
    'Mpumalanga',
    'Bushbuckridge Local Municipality',
  ),
  source(
    'Nkomazi Municipality Tenders',
    'municipality',
    'https://www.nkomazi.gov.za',
    'https://www.nkomazi.gov.za/tenders/',
    'Mpumalanga',
    'Nkomazi Local Municipality',
  ),
  source(
    'Thaba Chweu Municipality Tenders',
    'municipality',
    'https://www.tclm.gov.za',
    'https://www.tclm.gov.za/tenders/',
    'Mpumalanga',
    'Thaba Chweu Local Municipality',
  ),
  source(
    'Msukaligwa Municipality Tenders',
    'municipality',
    'https://www.msukaligwa.gov.za',
    'https://www.msukaligwa.gov.za/tenders/',
    'Mpumalanga',
    'Msukaligwa Local Municipality',
  ),
  source(
    'Nkangala District Municipality Tenders',
    'municipality',
    'https://www.nkangaladm.gov.za',
    'https://www.nkangaladm.gov.za/tenders/',
    'Mpumalanga',
    'Nkangala District Municipality',
  ),
  source(
    'Ehlanzeni District Municipality Tenders',
    'municipality',
    'https://www.ehlanzeni.gov.za',
    'https://www.ehlanzeni.gov.za/tenders/',
    'Mpumalanga',
    'Ehlanzeni District Municipality',
  ),
  source(
    'Gert Sibande District Municipality Tenders',
    'municipality',
    'https://www.gsibande.gov.za',
    'https://www.gsibande.gov.za/tenders/',
    'Mpumalanga',
    'Gert Sibande District Municipality',
  ),

  source(
    'Rustenburg Municipality Tenders',
    'municipality',
    'https://www.rustenburg.gov.za',
    'https://www.rustenburg.gov.za/tenders',
    'North West',
    'Rustenburg Local Municipality',
  ),
  source(
    'Madibeng Municipality Tenders',
    'municipality',
    'https://www.madibeng.gov.za',
    'https://www.madibeng.gov.za/tenders/',
    'North West',
    'Madibeng Local Municipality',
  ),
  source(
    'City of Matlosana Tenders',
    'municipality',
    'https://www.matlosana.gov.za',
    'https://www.matlosana.gov.za/tenders/',
    'North West',
    'City of Matlosana Local Municipality',
  ),
  source(
    'JB Marks Municipality Tenders',
    'municipality',
    'https://jbmarks.co.za',
    'https://jbmarks.co.za/tenders/',
    'North West',
    'JB Marks Local Municipality',
  ),
  source(
    'Mahikeng Municipality Tenders',
    'municipality',
    'https://www.mahikeng.gov.za',
    'https://www.mahikeng.gov.za/tenders/',
    'North West',
    'Mahikeng Local Municipality',
  ),
  source(
    'Bojanala Platinum District Municipality Tenders',
    'municipality',
    'https://www.bojanala.gov.za',
    'https://www.bojanala.gov.za/tenders/',
    'North West',
    'Bojanala Platinum District Municipality',
  ),
  source(
    'Dr Kenneth Kaunda District Municipality Tenders',
    'municipality',
    'https://www.kaundadistrict.gov.za',
    'https://www.kaundadistrict.gov.za/tenders/',
    'North West',
    'Dr Kenneth Kaunda District Municipality',
  ),
  source(
    'Ngaka Modiri Molema District Municipality Tenders',
    'municipality',
    'https://www.nmmdm.gov.za',
    'https://www.nmmdm.gov.za/tenders/',
    'North West',
    'Ngaka Modiri Molema District Municipality',
  ),
  source(
    'Dr Ruth Segomotsi Mompati District Municipality Tenders',
    'municipality',
    'https://www.rsmompatidm.gov.za',
    'https://www.rsmompatidm.gov.za/tenders/',
    'North West',
    'Dr Ruth Segomotsi Mompati District Municipality',
  ),

  source(
    'Sol Plaatje Municipality Tenders',
    'municipality',
    'https://www.solplaatje.org.za',
    'https://www.solplaatje.org.za/tenders/',
    'Northern Cape',
    'Sol Plaatje Local Municipality',
  ),
  source(
    'Dawid Kruiper Municipality Tenders',
    'municipality',
    'https://www.dawidkruiper.xyz',
    'https://www.dawidkruiper.xyz/tenders/',
    'Northern Cape',
    'Dawid Kruiper Local Municipality',
  ),
  source(
    'Frances Baard District Municipality Tenders',
    'municipality',
    'https://www.francesbaard.gov.za',
    'https://www.francesbaard.gov.za/tenders/',
    'Northern Cape',
    'Frances Baard District Municipality',
  ),
  source(
    'John Taolo Gaetsewe District Municipality Tenders',
    'municipality',
    'https://www.taologaetsewe.gov.za',
    'https://www.taologaetsewe.gov.za/tenders/',
    'Northern Cape',
    'John Taolo Gaetsewe District Municipality',
  ),
  source(
    'Namakwa District Municipality Tenders',
    'municipality',
    'https://www.namakwa-dm.gov.za',
    'https://www.namakwa-dm.gov.za/tenders/',
    'Northern Cape',
    'Namakwa District Municipality',
  ),
  source(
    'ZF Mgcawu District Municipality Tenders',
    'municipality',
    'https://www.zfm-dm.gov.za',
    'https://www.zfm-dm.gov.za/tenders/',
    'Northern Cape',
    'ZF Mgcawu District Municipality',
  ),

  source(
    'University of Cape Town Tenders',
    'university',
    'https://www.uct.ac.za',
    'https://www.uct.ac.za/main/procurement/tenders',
    'Western Cape',
    'University of Cape Town',
  ),
  source(
    'Stellenbosch University Tenders',
    'university',
    'https://www.sun.ac.za',
    'https://www.sun.ac.za/english/finance/procurement',
    'Western Cape',
    'Stellenbosch University',
  ),
  source(
    'University of Pretoria Tenders',
    'university',
    'https://www.up.ac.za',
    'https://www.up.ac.za/procurement',
    'Gauteng',
    'University of Pretoria',
  ),
  source(
    'University of the Witwatersrand Tenders',
    'university',
    'https://www.wits.ac.za',
    'https://www.wits.ac.za/about-wits/procurement/',
    'Gauteng',
    'University of the Witwatersrand',
  ),
  source(
    'University of Johannesburg Tenders',
    'university',
    'https://www.uj.ac.za',
    'https://www.uj.ac.za/supply-chain-management/',
    'Gauteng',
    'University of Johannesburg',
  ),
  source(
    'University of KwaZulu-Natal Tenders',
    'university',
    'https://ukzn.ac.za',
    'https://ukzn.ac.za/tenders/',
    'KwaZulu-Natal',
    'University of KwaZulu-Natal',
  ),
  source(
    'UNISA Tenders',
    'university',
    'https://www.unisa.ac.za',
    'https://www.unisa.ac.za/sites/corporate/default/Tenders',
    'Gauteng',
    'University of South Africa',
  ),
  source(
    'Durban University of Technology Tenders',
    'university',
    'https://www.dut.ac.za',
    'https://www.dut.ac.za/procurement/tenders/',
    'KwaZulu-Natal',
    'Durban University of Technology',
  ),
  source(
    'Tshwane University of Technology Tenders',
    'university',
    'https://www.tut.ac.za',
    'https://www.tut.ac.za/procurement/tenders',
    'Gauteng',
    'Tshwane University of Technology',
  ),
  source(
    'Cape Peninsula University of Technology Tenders',
    'university',
    'https://www.cput.ac.za',
    'https://www.cput.ac.za/about/procurement/tenders',
    'Western Cape',
    'Cape Peninsula University of Technology',
  ),
  source(
    'North-West University Tenders',
    'university',
    'https://www.nwu.ac.za',
    'https://www.nwu.ac.za/procurement/tenders',
    'North West',
    'North-West University',
  ),
  source(
    'University of the Free State Tenders',
    'university',
    'https://www.ufs.ac.za',
    'https://www.ufs.ac.za/supportservices/departments/finance-home/procurement/tenders',
    'Free State',
    'University of the Free State',
  ),
  source(
    'Rhodes University Tenders',
    'university',
    'https://www.ru.ac.za',
    'https://www.ru.ac.za/procurement/tenders/',
    'Eastern Cape',
    'Rhodes University',
  ),
  source(
    'Nelson Mandela University Tenders',
    'university',
    'https://www.mandela.ac.za',
    'https://www.mandela.ac.za/Procurement/Tenders',
    'Eastern Cape',
    'Nelson Mandela University',
  ),
  source(
    'University of Fort Hare Tenders',
    'university',
    'https://www.ufh.ac.za',
    'https://www.ufh.ac.za/tenders',
    'Eastern Cape',
    'University of Fort Hare',
  ),
  source(
    'University of Venda Tenders',
    'university',
    'https://www.univen.ac.za',
    'https://www.univen.ac.za/tenders/',
    'Limpopo',
    'University of Venda',
  ),
  source(
    'University of Limpopo Tenders',
    'university',
    'https://www.ul.ac.za',
    'https://www.ul.ac.za/tenders/',
    'Limpopo',
    'University of Limpopo',
  ),
  source(
    'Walter Sisulu University Tenders',
    'university',
    'https://www.wsu.ac.za',
    'https://www.wsu.ac.za/tenders/',
    'Eastern Cape',
    'Walter Sisulu University',
  ),
  source(
    'Central University of Technology Tenders',
    'university',
    'https://www.cut.ac.za',
    'https://www.cut.ac.za/tenders',
    'Free State',
    'Central University of Technology',
  ),
  source(
    'Vaal University of Technology Tenders',
    'university',
    'https://www.vut.ac.za',
    'https://www.vut.ac.za/tenders/',
    'Gauteng',
    'Vaal University of Technology',
  ),
  source(
    'Mangosuthu University of Technology Tenders',
    'university',
    'https://www.mut.ac.za',
    'https://www.mut.ac.za/tenders/',
    'KwaZulu-Natal',
    'Mangosuthu University of Technology',
  ),
  source(
    'South Cape TVET College Tenders',
    'tvet',
    'https://www.sccollege.co.za',
    'https://www.sccollege.co.za/tenders/',
    'Western Cape',
    'South Cape TVET College',
  ),
  source(
    'False Bay TVET College Tenders',
    'tvet',
    'https://www.falsebaycollege.co.za',
    'https://www.falsebaycollege.co.za/tenders/',
    'Western Cape',
    'False Bay TVET College',
  ),
  source(
    'Tshwane North TVET College Tenders',
    'tvet',
    'https://www.tnc.edu.za',
    'https://www.tnc.edu.za/tenders/',
    'Gauteng',
    'Tshwane North TVET College',
  ),
  source(
    'Ekurhuleni West TVET College Tenders',
    'tvet',
    'https://www.ewc.edu.za',
    'https://www.ewc.edu.za/tenders/',
    'Gauteng',
    'Ekurhuleni West TVET College',
  ),
  source(
    'Motheo TVET College Tenders',
    'tvet',
    'https://www.motheotvet.edu.za',
    'https://www.motheotvet.edu.za/tenders/',
    'Free State',
    'Motheo TVET College',
  ),
  source(
    'Capricorn TVET College Tenders',
    'tvet',
    'https://capricorncollege.edu.za',
    'https://capricorncollege.edu.za/tenders/',
    'Limpopo',
    'Capricorn TVET College',
  ),
  source(
    'Orbit TVET College Tenders',
    'tvet',
    'https://www.orbitcollege.co.za',
    'https://www.orbitcollege.co.za/tenders/',
    'North West',
    'Orbit TVET College',
  ),
  source(
    'Nkangala TVET College Tenders',
    'tvet',
    'https://www.ntc.edu.za',
    'https://www.ntc.edu.za/tenders/',
    'Mpumalanga',
    'Nkangala TVET College',
  ),
  source(
    'King Hintsa TVET College Tenders',
    'tvet',
    'https://www.kinghintsacollege.edu.za',
    'https://www.kinghintsacollege.edu.za/tenders/',
    'Eastern Cape',
    'King Hintsa TVET College',
  ),
  source(
    'Northern Cape Urban TVET College Tenders',
    'tvet',
    'https://ncutvet.edu.za',
    'https://ncutvet.edu.za/tenders/',
    'Northern Cape',
    'Northern Cape Urban TVET College',
  ),
];

export const southAfricanExternalSources: ExternalSourceSeed[] = [
  ...curatedSouthAfricanExternalSources,
  ...generatedTenderAdvertisingSources,
];
