// South African Municipalities Data for SEO and Filtering
// Source: Municipal Demarcation Board

export interface Municipality {
    province: string;
    name: string;
    type: 'Metropolitan' | 'District' | 'Local';
    slug: string;
}

export const PROVINCES = [
    { name: 'Eastern Cape', slug: 'eastern-cape' },
    { name: 'Free State', slug: 'free-state' },
    { name: 'Gauteng', slug: 'gauteng' },
    { name: 'KwaZulu-Natal', slug: 'kwazulu-natal' },
    { name: 'Limpopo', slug: 'limpopo' },
    { name: 'Mpumalanga', slug: 'mpumalanga' },
    { name: 'North West', slug: 'north-west' },
    { name: 'Northern Cape', slug: 'northern-cape' },
    { name: 'Western Cape', slug: 'western-cape' },
] as const;

export type ProvinceSlug = typeof PROVINCES[number]['slug'];

export const MUNICIPALITIES: Municipality[] = [
    // Eastern Cape (31 municipalities)
    { province: 'Eastern Cape', name: 'Buffalo City', type: 'Metropolitan', slug: 'buffalo-city' },
    { province: 'Eastern Cape', name: 'Nelson Mandela Bay', type: 'Metropolitan', slug: 'nelson-mandela-bay' },
    { province: 'Eastern Cape', name: 'Matatiele', type: 'Local', slug: 'matatiele' },
    { province: 'Eastern Cape', name: 'Kouga', type: 'Local', slug: 'kouga' },
    { province: 'Eastern Cape', name: 'Makana', type: 'Local', slug: 'makana' },
    { province: 'Eastern Cape', name: 'Ndlambe', type: 'Local', slug: 'ndlambe' },
    { province: 'Eastern Cape', name: 'Sundays River Valley', type: 'Local', slug: 'sundays-river-valley' },
    { province: 'Eastern Cape', name: 'Dr Beyers Naude', type: 'Local', slug: 'dr-beyers-naude' },
    { province: 'Eastern Cape', name: 'Blue Crane Route', type: 'Local', slug: 'blue-crane-route' },
    { province: 'Eastern Cape', name: 'Amahlathi', type: 'Local', slug: 'amahlathi' },
    { province: 'Eastern Cape', name: 'Great Kei', type: 'Local', slug: 'great-kei' },
    { province: 'Eastern Cape', name: 'Ngqushwa', type: 'Local', slug: 'ngqushwa' },
    { province: 'Eastern Cape', name: 'Raymond Mhlaba', type: 'Local', slug: 'raymond-mhlaba' },
    { province: 'Eastern Cape', name: 'Inxuba Yethemba', type: 'Local', slug: 'inxuba-yethemba' },
    { province: 'Eastern Cape', name: 'Enoch Mgijima', type: 'Local', slug: 'enoch-mgijima' },
    { province: 'Eastern Cape', name: 'Emalahleni', type: 'Local', slug: 'emalahleni-ec' },
    { province: 'Eastern Cape', name: 'Intsika Yethu', type: 'Local', slug: 'intsika-yethu' },
    { province: 'Eastern Cape', name: 'Sakhisizwe', type: 'Local', slug: 'sakhisizwe' },
    { province: 'Eastern Cape', name: 'Engcobo', type: 'Local', slug: 'engcobo' },
    { province: 'Eastern Cape', name: 'Elundini', type: 'Local', slug: 'elundini' },
    { province: 'Eastern Cape', name: 'Senqu', type: 'Local', slug: 'senqu' },
    { province: 'Eastern Cape', name: 'Walter Sisulu', type: 'Local', slug: 'walter-sisulu' },
    { province: 'Eastern Cape', name: 'Ingquza Hill', type: 'Local', slug: 'ingquza-hill' },
    { province: 'Eastern Cape', name: 'Port St Johns', type: 'Local', slug: 'port-st-johns' },
    { province: 'Eastern Cape', name: 'Nyandeni', type: 'Local', slug: 'nyandeni' },
    { province: 'Eastern Cape', name: 'Mhlontlo', type: 'Local', slug: 'mhlontlo' },
    { province: 'Eastern Cape', name: 'King Sabata Dalindyebo', type: 'Local', slug: 'king-sabata-dalindyebo' },
    { province: 'Eastern Cape', name: 'Mbizana', type: 'Local', slug: 'mbizana' },
    { province: 'Eastern Cape', name: 'Ntabankulu', type: 'Local', slug: 'ntabankulu' },
    { province: 'Eastern Cape', name: 'Umzimvubu', type: 'Local', slug: 'umzimvubu' },
    { province: 'Eastern Cape', name: 'Winnie Madikizela-Mandela', type: 'Local', slug: 'winnie-madikizela-mandela' },

    // Free State (19 municipalities)
    { province: 'Free State', name: 'Mangaung', type: 'Metropolitan', slug: 'mangaung' },
    { province: 'Free State', name: 'Matjhabeng', type: 'Local', slug: 'matjhabeng' },
    { province: 'Free State', name: 'Maluti-A-Phofung', type: 'Local', slug: 'maluti-a-phofung' },
    { province: 'Free State', name: 'Dihlabeng', type: 'Local', slug: 'dihlabeng' },
    { province: 'Free State', name: 'Metsimaholo', type: 'Local', slug: 'metsimaholo' },
    { province: 'Free State', name: 'Moqhaka', type: 'Local', slug: 'moqhaka' },
    { province: 'Free State', name: 'Ngwathe', type: 'Local', slug: 'ngwathe' },
    { province: 'Free State', name: 'Setsoto', type: 'Local', slug: 'setsoto' },
    { province: 'Free State', name: 'Nketoana', type: 'Local', slug: 'nketoana' },
    { province: 'Free State', name: 'Phumelela', type: 'Local', slug: 'phumelela' },
    { province: 'Free State', name: 'Mantsopa', type: 'Local', slug: 'mantsopa' },
    { province: 'Free State', name: 'Nala', type: 'Local', slug: 'nala' },
    { province: 'Free State', name: 'Tokologo', type: 'Local', slug: 'tokologo' },
    { province: 'Free State', name: 'Tswelopele', type: 'Local', slug: 'tswelopele' },
    { province: 'Free State', name: 'Letsemeng', type: 'Local', slug: 'letsemeng' },
    { province: 'Free State', name: 'Kopanong', type: 'Local', slug: 'kopanong' },
    { province: 'Free State', name: 'Mohokare', type: 'Local', slug: 'mohokare' },
    { province: 'Free State', name: 'Mafube', type: 'Local', slug: 'mafube' },
    { province: 'Free State', name: 'Masilonyana', type: 'Local', slug: 'masilonyana' },

    // Gauteng (11 municipalities)
    { province: 'Gauteng', name: 'City of Johannesburg', type: 'Metropolitan', slug: 'johannesburg' },
    { province: 'Gauteng', name: 'City of Tshwane', type: 'Metropolitan', slug: 'tshwane' },
    { province: 'Gauteng', name: 'City of Ekurhuleni', type: 'Metropolitan', slug: 'ekurhuleni' },
    { province: 'Gauteng', name: 'Emfuleni', type: 'Local', slug: 'emfuleni' },
    { province: 'Gauteng', name: 'Lesedi', type: 'Local', slug: 'lesedi' },
    { province: 'Gauteng', name: 'Midvaal', type: 'Local', slug: 'midvaal' },
    { province: 'Gauteng', name: 'Merafong City', type: 'Local', slug: 'merafong-city' },
    { province: 'Gauteng', name: 'Mogale City', type: 'Local', slug: 'mogale-city' },
    { province: 'Gauteng', name: 'Rand West City', type: 'Local', slug: 'rand-west-city' },
    { province: 'Gauteng', name: 'Sedibeng', type: 'Local', slug: 'sedibeng' },
    { province: 'Gauteng', name: 'West Rand', type: 'Local', slug: 'west-rand' },

    // KwaZulu-Natal (54 municipalities)
    { province: 'KwaZulu-Natal', name: 'eThekwini', type: 'Metropolitan', slug: 'ethekwini' },
    { province: 'KwaZulu-Natal', name: 'Msunduzi', type: 'Local', slug: 'msunduzi' },
    { province: 'KwaZulu-Natal', name: 'uMhlathuze', type: 'Local', slug: 'umhlathuze' },
    { province: 'KwaZulu-Natal', name: 'Newcastle', type: 'Local', slug: 'newcastle' },
    { province: 'KwaZulu-Natal', name: 'Ray Nkonyeni', type: 'Local', slug: 'ray-nkonyeni' },
    { province: 'KwaZulu-Natal', name: 'Alfred Duma', type: 'Local', slug: 'alfred-duma' },
    { province: 'KwaZulu-Natal', name: 'uMngeni', type: 'Local', slug: 'umngeni' },
    { province: 'KwaZulu-Natal', name: 'KwaDukuza', type: 'Local', slug: 'kwadukuza' },
    { province: 'KwaZulu-Natal', name: 'AbaQulusi', type: 'Local', slug: 'abaqulusi' },
    { province: 'KwaZulu-Natal', name: 'uMlalazi', type: 'Local', slug: 'umlalazi' },
    { province: 'KwaZulu-Natal', name: 'Mthonjaneni', type: 'Local', slug: 'mthonjaneni' },
    { province: 'KwaZulu-Natal', name: 'Nongoma', type: 'Local', slug: 'nongoma' },
    { province: 'KwaZulu-Natal', name: 'Ulundi', type: 'Local', slug: 'ulundi' },
    { province: 'KwaZulu-Natal', name: 'Nkandla', type: 'Local', slug: 'nkandla' },
    { province: 'KwaZulu-Natal', name: 'uMhlabuyalingana', type: 'Local', slug: 'umhlabuyalingana' },
    { province: 'KwaZulu-Natal', name: 'Jozini', type: 'Local', slug: 'jozini' },
    { province: 'KwaZulu-Natal', name: 'Big 5 Hlabisa', type: 'Local', slug: 'big-5-hlabisa' },
    { province: 'KwaZulu-Natal', name: 'uMfolozi', type: 'Local', slug: 'umfolozi' },
    { province: 'KwaZulu-Natal', name: 'Mandeni', type: 'Local', slug: 'mandeni' },
    { province: 'KwaZulu-Natal', name: 'Maphumulo', type: 'Local', slug: 'maphumulo' },
    { province: 'KwaZulu-Natal', name: 'Ndwedwe', type: 'Local', slug: 'ndwedwe' },
    { province: 'KwaZulu-Natal', name: 'Ubuhlebezwe', type: 'Local', slug: 'ubuhlebezwe' },
    { province: 'KwaZulu-Natal', name: 'Umzumbe', type: 'Local', slug: 'umzumbe' },
    { province: 'KwaZulu-Natal', name: 'uMzimkhulu', type: 'Local', slug: 'umzimkhulu' },
    { province: 'KwaZulu-Natal', name: 'Dannhauser', type: 'Local', slug: 'dannhauser' },
    { province: 'KwaZulu-Natal', name: 'eDumbe', type: 'Local', slug: 'edumbe' },
    { province: 'KwaZulu-Natal', name: 'uPhongolo', type: 'Local', slug: 'uphongolo' },
    { province: 'KwaZulu-Natal', name: 'Nqutu', type: 'Local', slug: 'nqutu' },
    { province: 'KwaZulu-Natal', name: 'uMvoti', type: 'Local', slug: 'umvoti' },
    { province: 'KwaZulu-Natal', name: 'Impendle', type: 'Local', slug: 'impendle' },
    { province: 'KwaZulu-Natal', name: 'Richmond', type: 'Local', slug: 'richmond-kzn' },
    { province: 'KwaZulu-Natal', name: 'Mkhambathini', type: 'Local', slug: 'mkhambathini' },
    { province: 'KwaZulu-Natal', name: 'Okhahlamba', type: 'Local', slug: 'okhahlamba' },
    { province: 'KwaZulu-Natal', name: 'Imbabazane', type: 'Local', slug: 'imbabazane' },
    { province: 'KwaZulu-Natal', name: 'Inkosi Langalibalele', type: 'Local', slug: 'inkosi-langalibalele' },
    { province: 'KwaZulu-Natal', name: 'Umtshezi', type: 'Local', slug: 'umtshezi' },
    { province: 'KwaZulu-Natal', name: 'Endumeni', type: 'Local', slug: 'endumeni' },
    { province: 'KwaZulu-Natal', name: 'Nquthu', type: 'Local', slug: 'nquthu' },
    { province: 'KwaZulu-Natal', name: 'Msinga', type: 'Local', slug: 'msinga' },
    { province: 'KwaZulu-Natal', name: 'uMshwathi', type: 'Local', slug: 'umshwathi' },
    { province: 'KwaZulu-Natal', name: 'iLembe', type: 'Local', slug: 'ilembe' },
    { province: 'KwaZulu-Natal', name: 'Dr Nkosazana Dlamini-Zuma', type: 'Local', slug: 'dr-nkosazana-dlamini-zuma' },
    { province: 'KwaZulu-Natal', name: 'Greater Kokstad', type: 'Local', slug: 'greater-kokstad' },
    { province: 'KwaZulu-Natal', name: 'Umuziwabantu', type: 'Local', slug: 'umuziwabantu' },
    { province: 'KwaZulu-Natal', name: 'Ezinqoleni', type: 'Local', slug: 'ezinqoleni' },
    { province: 'KwaZulu-Natal', name: 'Umdoni', type: 'Local', slug: 'umdoni' },
    { province: 'KwaZulu-Natal', name: 'Vulamehlo', type: 'Local', slug: 'vulamehlo' },
    { province: 'KwaZulu-Natal', name: 'Mtubatuba', type: 'Local', slug: 'mtubatuba' },
    { province: 'KwaZulu-Natal', name: 'Nkandla', type: 'Local', slug: 'nkandla-kzn' },
    { province: 'KwaZulu-Natal', name: 'uMuziwabantu', type: 'Local', slug: 'umuziwabantu-kzn' },
    { province: 'KwaZulu-Natal', name: 'Hlabisa', type: 'Local', slug: 'hlabisa' },
    { province: 'KwaZulu-Natal', name: 'Emadlangeni', type: 'Local', slug: 'emadlangeni' },
    { province: 'KwaZulu-Natal', name: 'Ntambanana', type: 'Local', slug: 'ntambanana' },
    { province: 'KwaZulu-Natal', name: 'uMuziwabantu', type: 'Local', slug: 'umuziwabantu-2' },

    // Limpopo (22 municipalities)
    { province: 'Limpopo', name: 'Polokwane', type: 'Local', slug: 'polokwane' },
    { province: 'Limpopo', name: 'Mogalakwena', type: 'Local', slug: 'mogalakwena' },
    { province: 'Limpopo', name: 'Thulamela', type: 'Local', slug: 'thulamela' },
    { province: 'Limpopo', name: 'Makhado', type: 'Local', slug: 'makhado' },
    { province: 'Limpopo', name: 'Greater Tzaneen', type: 'Local', slug: 'greater-tzaneen' },
    { province: 'Limpopo', name: 'Greater Giyani', type: 'Local', slug: 'greater-giyani' },
    { province: 'Limpopo', name: 'Ba-Phalaborwa', type: 'Local', slug: 'ba-phalaborwa' },
    { province: 'Limpopo', name: 'Elias Motsoaledi', type: 'Local', slug: 'elias-motsoaledi' },
    { province: 'Limpopo', name: 'Fetakgomo Tubatse', type: 'Local', slug: 'fetakgomo-tubatse' },
    { province: 'Limpopo', name: 'Musina', type: 'Local', slug: 'musina' },
    { province: 'Limpopo', name: 'Collins Chabane', type: 'Local', slug: 'collins-chabane' },
    { province: 'Limpopo', name: 'Lephalale', type: 'Local', slug: 'lephalale' },
    { province: 'Limpopo', name: 'Bela-Bela', type: 'Local', slug: 'bela-bela' },
    { province: 'Limpopo', name: 'Modimolle-Mookgophong', type: 'Local', slug: 'modimolle-mookgophong' },
    { province: 'Limpopo', name: 'Thabazimbi', type: 'Local', slug: 'thabazimbi' },
    { province: 'Limpopo', name: 'Maruleng', type: 'Local', slug: 'maruleng' },
    { province: 'Limpopo', name: 'Greater Letaba', type: 'Local', slug: 'greater-letaba' },
    { province: 'Limpopo', name: 'Makhuduthamaga', type: 'Local', slug: 'makhuduthamaga' },
    { province: 'Limpopo', name: 'Ephraim Mogale', type: 'Local', slug: 'ephraim-mogale' },
    { province: 'Limpopo', name: 'Lepelle-Nkumpi', type: 'Local', slug: 'lepelle-nkumpi' },
    { province: 'Limpopo', name: 'Blouberg', type: 'Local', slug: 'blouberg' },
    { province: 'Limpopo', name: 'Molemole', type: 'Local', slug: 'molemole' },

    // Mpumalanga (20 municipalities)
    { province: 'Mpumalanga', name: 'City of Mbombela', type: 'Local', slug: 'mbombela' },
    { province: 'Mpumalanga', name: 'Emalahleni', type: 'Local', slug: 'emalahleni-mp' },
    { province: 'Mpumalanga', name: 'Steve Tshwete', type: 'Local', slug: 'steve-tshwete' },
    { province: 'Mpumalanga', name: 'Govan Mbeki', type: 'Local', slug: 'govan-mbeki' },
    { province: 'Mpumalanga', name: 'Bushbuckridge', type: 'Local', slug: 'bushbuckridge' },
    { province: 'Mpumalanga', name: 'Nkomazi', type: 'Local', slug: 'nkomazi' },
    { province: 'Mpumalanga', name: 'Thaba Chweu', type: 'Local', slug: 'thaba-chweu' },
    { province: 'Mpumalanga', name: 'Chief Albert Luthuli', type: 'Local', slug: 'chief-albert-luthuli' },
    { province: 'Mpumalanga', name: 'Msukaligwa', type: 'Local', slug: 'msukaligwa' },
    { province: 'Mpumalanga', name: 'Mkhondo', type: 'Local', slug: 'mkhondo' },
    { province: 'Mpumalanga', name: 'Pixley Ka Seme', type: 'Local', slug: 'pixley-ka-seme' },
    { province: 'Mpumalanga', name: 'Lekwa', type: 'Local', slug: 'lekwa' },
    { province: 'Mpumalanga', name: 'Dipaleseng', type: 'Local', slug: 'dipaleseng' },
    { province: 'Mpumalanga', name: 'Victor Khanye', type: 'Local', slug: 'victor-khanye' },
    { province: 'Mpumalanga', name: 'Emakhazeni', type: 'Local', slug: 'emakhazeni' },
    { province: 'Mpumalanga', name: 'Thembisile Hani', type: 'Local', slug: 'thembisile-hani' },
    { province: 'Mpumalanga', name: 'Dr JS Moroka', type: 'Local', slug: 'dr-js-moroka' },
    { province: 'Mpumalanga', name: 'Albert Luthuli', type: 'Local', slug: 'albert-luthuli' },
    { province: 'Mpumalanga', name: 'Dr Pixley Ka Isaka Seme', type: 'Local', slug: 'dr-pixley-ka-isaka-seme' },
    { province: 'Mpumalanga', name: 'Nkangala', type: 'Local', slug: 'nkangala' },

    // North West (22 municipalities)
    { province: 'North West', name: 'Rustenburg', type: 'Local', slug: 'rustenburg' },
    { province: 'North West', name: 'Madibeng', type: 'Local', slug: 'madibeng' },
    { province: 'North West', name: 'City of Matlosana', type: 'Local', slug: 'matlosana' },
    { province: 'North West', name: 'JB Marks', type: 'Local', slug: 'jb-marks' },
    { province: 'North West', name: 'Mahikeng', type: 'Local', slug: 'mahikeng' },
    { province: 'North West', name: 'Ditsobotla', type: 'Local', slug: 'ditsobotla' },
    { province: 'North West', name: 'Moretele', type: 'Local', slug: 'moretele' },
    { province: 'North West', name: 'Moses Kotane', type: 'Local', slug: 'moses-kotane' },
    { province: 'North West', name: 'Kgetlengrivier', type: 'Local', slug: 'kgetlengrivier' },
    { province: 'North West', name: 'Maquassi Hills', type: 'Local', slug: 'maquassi-hills' },
    { province: 'North West', name: 'Lekwa-Teemane', type: 'Local', slug: 'lekwa-teemane' },
    { province: 'North West', name: 'Mamusa', type: 'Local', slug: 'mamusa' },
    { province: 'North West', name: 'Greater Taung', type: 'Local', slug: 'greater-taung' },
    { province: 'North West', name: 'Naledi', type: 'Local', slug: 'naledi' },
    { province: 'North West', name: 'Kagisano-Molopo', type: 'Local', slug: 'kagisano-molopo' },
    { province: 'North West', name: 'Ramotshere Moiloa', type: 'Local', slug: 'ramotshere-moiloa' },
    { province: 'North West', name: 'Ratlou', type: 'Local', slug: 'ratlou' },
    { province: 'North West', name: 'Tswaing', type: 'Local', slug: 'tswaing' },
    { province: 'North West', name: 'Mafikeng', type: 'Local', slug: 'mafikeng' },
    { province: 'North West', name: 'Ventersdorp/Tlokwe', type: 'Local', slug: 'ventersdorp-tlokwe' },
    { province: 'North West', name: 'Bojanala Platinum', type: 'Local', slug: 'bojanala-platinum' },
    { province: 'North West', name: 'Ngaka Modiri Molema', type: 'Local', slug: 'ngaka-modiri-molema' },

    // Northern Cape (32 municipalities)
    { province: 'Northern Cape', name: 'Sol Plaatje', type: 'Local', slug: 'sol-plaatje' },
    { province: 'Northern Cape', name: 'Dawid Kruiper', type: 'Local', slug: 'dawid-kruiper' },
    { province: 'Northern Cape', name: 'Ga-Segonyana', type: 'Local', slug: 'ga-segonyana' },
    { province: 'Northern Cape', name: 'Gamagara', type: 'Local', slug: 'gamagara' },
    { province: 'Northern Cape', name: 'Tsantsabane', type: 'Local', slug: 'tsantsabane' },
    { province: 'Northern Cape', name: 'Kai !Garib', type: 'Local', slug: 'kai-garib' },
    { province: 'Northern Cape', name: '!Kheis', type: 'Local', slug: 'kheis' },
    { province: 'Northern Cape', name: 'Joe Morolong', type: 'Local', slug: 'joe-morolong' },
    { province: 'Northern Cape', name: 'Richtersveld', type: 'Local', slug: 'richtersveld' },
    { province: 'Northern Cape', name: 'Nama Khoi', type: 'Local', slug: 'nama-khoi' },
    { province: 'Northern Cape', name: 'Kamiesberg', type: 'Local', slug: 'kamiesberg' },
    { province: 'Northern Cape', name: 'Hantam', type: 'Local', slug: 'hantam' },
    { province: 'Northern Cape', name: 'Karoo Hoogland', type: 'Local', slug: 'karoo-hoogland' },
    { province: 'Northern Cape', name: 'Khai-Ma', type: 'Local', slug: 'khai-ma' },
    { province: 'Northern Cape', name: 'Ubuntu', type: 'Local', slug: 'ubuntu' },
    { province: 'Northern Cape', name: 'Umsobomvu', type: 'Local', slug: 'umsobomvu' },
    { province: 'Northern Cape', name: 'Emthanjeni', type: 'Local', slug: 'emthanjeni' },
    { province: 'Northern Cape', name: 'Kareeberg', type: 'Local', slug: 'kareeberg' },
    { province: 'Northern Cape', name: 'Renosterberg', type: 'Local', slug: 'renosterberg' },
    { province: 'Northern Cape', name: 'Thembelihle', type: 'Local', slug: 'thembelihle' },
    { province: 'Northern Cape', name: 'Siyathemba', type: 'Local', slug: 'siyathemba' },
    { province: 'Northern Cape', name: 'Siyancuma', type: 'Local', slug: 'siyancuma' },
    { province: 'Northern Cape', name: 'Dikgatlong', type: 'Local', slug: 'dikgatlong' },
    { province: 'Northern Cape', name: 'Magareng', type: 'Local', slug: 'magareng' },
    { province: 'Northern Cape', name: 'Phokwane', type: 'Local', slug: 'phokwane' },
    { province: 'Northern Cape', name: 'ZF Mgcawu', type: 'Local', slug: 'zf-mgcawu' },
    { province: 'Northern Cape', name: 'John Taolo Gaetsewe', type: 'Local', slug: 'john-taolo-gaetsewe' },
    { province: 'Northern Cape', name: 'Frances Baard', type: 'Local', slug: 'frances-baard' },
    { province: 'Northern Cape', name: 'Pixley Ka Seme', type: 'Local', slug: 'pixley-ka-seme-nc' },
    { province: 'Northern Cape', name: 'Namakwa', type: 'Local', slug: 'namakwa' },
    { province: 'Northern Cape', name: 'Mier', type: 'Local', slug: 'mier' },
    { province: 'Northern Cape', name: 'Khara Hais', type: 'Local', slug: 'khara-hais' },

    // Western Cape (30 municipalities)
    { province: 'Western Cape', name: 'City of Cape Town', type: 'Metropolitan', slug: 'cape-town' },
    { province: 'Western Cape', name: 'Drakenstein', type: 'Local', slug: 'drakenstein' },
    { province: 'Western Cape', name: 'George', type: 'Local', slug: 'george' },
    { province: 'Western Cape', name: 'Stellenbosch', type: 'Local', slug: 'stellenbosch' },
    { province: 'Western Cape', name: 'Breede Valley', type: 'Local', slug: 'breede-valley' },
    { province: 'Western Cape', name: 'Saldanha Bay', type: 'Local', slug: 'saldanha-bay' },
    { province: 'Western Cape', name: 'Mossel Bay', type: 'Local', slug: 'mossel-bay' },
    { province: 'Western Cape', name: 'Overstrand', type: 'Local', slug: 'overstrand' },
    { province: 'Western Cape', name: 'Knysna', type: 'Local', slug: 'knysna' },
    { province: 'Western Cape', name: 'Oudtshoorn', type: 'Local', slug: 'oudtshoorn' },
    { province: 'Western Cape', name: 'Bitou', type: 'Local', slug: 'bitou' },
    { province: 'Western Cape', name: 'Cederberg', type: 'Local', slug: 'cederberg' },
    { province: 'Western Cape', name: 'Matzikama', type: 'Local', slug: 'matzikama' },
    { province: 'Western Cape', name: 'Bergrivier', type: 'Local', slug: 'bergrivier' },
    { province: 'Western Cape', name: 'Witzenberg', type: 'Local', slug: 'witzenberg' },
    { province: 'Western Cape', name: 'Theewaterskloof', type: 'Local', slug: 'theewaterskloof' },
    { province: 'Western Cape', name: 'Cape Agulhas', type: 'Local', slug: 'cape-agulhas' },
    { province: 'Western Cape', name: 'Swellendam', type: 'Local', slug: 'swellendam' },
    { province: 'Western Cape', name: 'Langeberg', type: 'Local', slug: 'langeberg' },
    { province: 'Western Cape', name: 'Hessequa', type: 'Local', slug: 'hessequa' },
    { province: 'Western Cape', name: 'Kannaland', type: 'Local', slug: 'kannaland' },
    { province: 'Western Cape', name: 'Prince Albert', type: 'Local', slug: 'prince-albert' },
    { province: 'Western Cape', name: 'Laingsburg', type: 'Local', slug: 'laingsburg' },
    { province: 'Western Cape', name: 'Beaufort West', type: 'Local', slug: 'beaufort-west' },
    { province: 'Western Cape', name: 'Swartland', type: 'Local', slug: 'swartland' },
    { province: 'Western Cape', name: 'West Coast', type: 'Local', slug: 'west-coast' },
    { province: 'Western Cape', name: 'Cape Winelands', type: 'Local', slug: 'cape-winelands' },
    { province: 'Western Cape', name: 'Central Karoo', type: 'Local', slug: 'central-karoo' },
    { province: 'Western Cape', name: 'Overberg', type: 'Local', slug: 'overberg' },
    { province: 'Western Cape', name: 'Garden Route', type: 'Local', slug: 'garden-route' },

    // District Municipalities (44 total)
    // Eastern Cape Districts
    { province: 'Eastern Cape', name: 'Amathole District', type: 'District', slug: 'amathole-district' },
    { province: 'Eastern Cape', name: 'Chris Hani District', type: 'District', slug: 'chris-hani-district' },
    { province: 'Eastern Cape', name: 'Joe Gqabi District', type: 'District', slug: 'joe-gqabi-district' },
    { province: 'Eastern Cape', name: 'OR Tambo District', type: 'District', slug: 'or-tambo-district' },
    { province: 'Eastern Cape', name: 'Alfred Nzo District', type: 'District', slug: 'alfred-nzo-district' },
    { province: 'Eastern Cape', name: 'Sarah Baartman District', type: 'District', slug: 'sarah-baartman-district' },
    // Free State Districts
    { province: 'Free State', name: 'Xhariep District', type: 'District', slug: 'xhariep-district' },
    { province: 'Free State', name: 'Lejweleputswa District', type: 'District', slug: 'lejweleputswa-district' },
    { province: 'Free State', name: 'Thabo Mofutsanyana District', type: 'District', slug: 'thabo-mofutsanyana-district' },
    { province: 'Free State', name: 'Fezile Dabi District', type: 'District', slug: 'fezile-dabi-district' },
    // Gauteng Districts
    { province: 'Gauteng', name: 'Sedibeng District', type: 'District', slug: 'sedibeng-district' },
    { province: 'Gauteng', name: 'West Rand District', type: 'District', slug: 'west-rand-district' },
    // KwaZulu-Natal Districts
    { province: 'KwaZulu-Natal', name: 'Amajuba District', type: 'District', slug: 'amajuba-district' },
    { province: 'KwaZulu-Natal', name: 'Harry Gwala District', type: 'District', slug: 'harry-gwala-district' },
    { province: 'KwaZulu-Natal', name: 'iLembe District', type: 'District', slug: 'ilembe-district' },
    { province: 'KwaZulu-Natal', name: 'King Cetshwayo District', type: 'District', slug: 'king-cetshwayo-district' },
    { province: 'KwaZulu-Natal', name: 'Ugu District', type: 'District', slug: 'ugu-district' },
    { province: 'KwaZulu-Natal', name: 'uMgungundlovu District', type: 'District', slug: 'umgungundlovu-district' },
    { province: 'KwaZulu-Natal', name: 'uMkhanyakude District', type: 'District', slug: 'umkhanyakude-district' },
    { province: 'KwaZulu-Natal', name: 'uMzinyathi District', type: 'District', slug: 'umzinyathi-district' },
    { province: 'KwaZulu-Natal', name: 'uThukela District', type: 'District', slug: 'uthukela-district' },
    { province: 'KwaZulu-Natal', name: 'Zululand District', type: 'District', slug: 'zululand-district' },
    // Limpopo Districts
    { province: 'Limpopo', name: 'Capricorn District', type: 'District', slug: 'capricorn-district' },
    { province: 'Limpopo', name: 'Mopani District', type: 'District', slug: 'mopani-district' },
    { province: 'Limpopo', name: 'Sekhukhune District', type: 'District', slug: 'sekhukhune-district' },
    { province: 'Limpopo', name: 'Vhembe District', type: 'District', slug: 'vhembe-district' },
    { province: 'Limpopo', name: 'Waterberg District', type: 'District', slug: 'waterberg-district' },
    // Mpumalanga Districts
    { province: 'Mpumalanga', name: 'Ehlanzeni District', type: 'District', slug: 'ehlanzeni-district' },
    { province: 'Mpumalanga', name: 'Gert Sibande District', type: 'District', slug: 'gert-sibande-district' },
    { province: 'Mpumalanga', name: 'Nkangala District', type: 'District', slug: 'nkangala-district' },
    // North West Districts
    { province: 'North West', name: 'Bojanala Platinum District', type: 'District', slug: 'bojanala-platinum-district' },
    { province: 'North West', name: 'Dr Kenneth Kaunda District', type: 'District', slug: 'dr-kenneth-kaunda-district' },
    { province: 'North West', name: 'Dr Ruth Segomotsi Mompati District', type: 'District', slug: 'dr-ruth-segomotsi-mompati-district' },
    { province: 'North West', name: 'Ngaka Modiri Molema District', type: 'District', slug: 'ngaka-modiri-molema-district' },
    // Northern Cape Districts
    { province: 'Northern Cape', name: 'Frances Baard District', type: 'District', slug: 'frances-baard-district' },
    { province: 'Northern Cape', name: 'John Taolo Gaetsewe District', type: 'District', slug: 'john-taolo-gaetsewe-district' },
    { province: 'Northern Cape', name: 'Namakwa District', type: 'District', slug: 'namakwa-district' },
    { province: 'Northern Cape', name: 'Pixley Ka Seme District', type: 'District', slug: 'pixley-ka-seme-district' },
    { province: 'Northern Cape', name: 'ZF Mgcawu District', type: 'District', slug: 'zf-mgcawu-district' },
    // Western Cape Districts
    { province: 'Western Cape', name: 'Cape Winelands District', type: 'District', slug: 'cape-winelands-district' },
    { province: 'Western Cape', name: 'Central Karoo District', type: 'District', slug: 'central-karoo-district' },
    { province: 'Western Cape', name: 'Garden Route District', type: 'District', slug: 'garden-route-district' },
    { province: 'Western Cape', name: 'Overberg District', type: 'District', slug: 'overberg-district' },
    { province: 'Western Cape', name: 'West Coast District', type: 'District', slug: 'west-coast-district' },
];

// Helper functions
export function getMunicipalitiesByProvince(province: string): Municipality[] {
    return MUNICIPALITIES.filter(m => m.province === province);
}

export function getProvinceBySlug(slug: string) {
    return PROVINCES.find(p => p.slug === slug);
}

export function getMunicipalityBySlug(slug: string) {
    return MUNICIPALITIES.find(m => m.slug === slug);
}

// SEO Sectors
export const SECTORS = [
    {
        name: 'Construction',
        slug: 'construction',
        keywords: ['CIDB tenders', 'construction tenders SA', 'civil engineering tenders', 'building tenders'],
        description: 'Find construction, civil engineering, and building tenders across South Africa. CIDB registered contractors welcome.',
    },
    {
        name: 'Cleaning',
        slug: 'cleaning',
        keywords: ['cleaning tenders', 'cleaning services tenders', 'janitorial tenders', 'sanitation tenders'],
        description: 'Browse cleaning service tenders from government departments, schools, hospitals, and municipalities.',
    },
    {
        name: 'Security',
        slug: 'security',
        keywords: ['security tenders South Africa', 'guarding tenders', 'PSIRA tenders', 'surveillance tenders'],
        description: 'Security services tenders including guarding, surveillance, and access control for government facilities.',
    },
    {
        name: 'IT & Technology',
        slug: 'it',
        keywords: ['IT tenders South Africa', 'software tenders', 'technology tenders', 'ICT tenders'],
        description: 'Information technology, software development, and ICT infrastructure tenders from public sector.',
    },
    {
        name: 'Medical & Healthcare',
        slug: 'medical',
        keywords: ['medical tenders', 'PPE tenders', 'healthcare tenders', 'pharmaceutical tenders'],
        description: 'Healthcare, medical supplies, PPE, and pharmaceutical tenders from hospitals and health departments.',
    },
    {
        name: 'Catering',
        slug: 'catering',
        keywords: ['catering tenders', 'food services tenders', 'school feeding tenders', 'hospitality tenders'],
        description: 'Food service and catering tenders for schools, hospitals, government events, and institutions.',
    },
    {
        name: 'Transport & Logistics',
        slug: 'transport',
        keywords: ['transport tenders', 'logistics tenders', 'fleet tenders', 'courier tenders'],
        description: 'Transport, logistics, fleet management, and courier service tenders from government departments.',
    },
] as const;

export type SectorSlug = typeof SECTORS[number]['slug'];

export function getSectorBySlug(slug: string) {
    return SECTORS.find(s => s.slug === slug);
}
